"""Runtime detector registry (generated by src.detection.calibrate).

One registry: `data/detectors/registry.json`, written by calibration and
read (never hand-edited) at runtime. Delhi is intentionally absent: its
frozen ensemble detector is served through the station mapping and is
never touched by this registry.
"""

from __future__ import annotations

import json
from pathlib import Path

REGISTRY_PATH = Path("data/detectors/registry.json")

# Fields every entry must expose for serving (Phase 25 capability contract).
ENTRY_FIELDS = ("station_id", "city", "capability", "detector_available",
                "detector_type", "cadence", "pressure_semantics",
                "rh_provenance", "data_mode")

_cache: dict[tuple, dict] = {}


def load(root: str | Path = ".") -> dict:
    """Load the detector registry; empty when not yet calibrated."""
    key = (str(Path(root).resolve()),)
    if key in _cache:
        return _cache[key]
    path = Path(root) / REGISTRY_PATH
    if not path.is_file():
        _cache[key] = {"version": 1, "detectors": []}
        return _cache[key]
    _cache[key] = json.loads(path.read_text(encoding="utf-8"))
    return _cache[key]


def reset_cache() -> None:
    """Drop cached registries (called after calibration rewrites the file)."""
    _cache.clear()


def entries(root: str | Path = ".") -> list[dict]:
    """All calibrated detector entries (empty when none are calibrated)."""
    return list(load(root).get("detectors", []))


def get(root: str | Path, backend_id: str) -> dict | None:
    """Detector entry for a backend station ID, or None."""
    for entry in entries(root):
        if entry.get("backend_station_id") == backend_id:
            return entry
    return None


def get_by_frontend_id(root: str | Path, station_id: str) -> dict | None:
    """Detector entry for a frontend/city station ID, or None."""
    for entry in entries(root):
        if entry.get("station_id") == station_id:
            return entry
    return None


def artifact_path(root: str | Path, entry: dict) -> Path:
    """Absolute path of a registry entry's calibration artifact."""
    return Path(root) / entry["artifact"]


def replayable_entries(store) -> list[dict]:
    """Mapping entries with a calibrated statistical detector."""
    registry = load(getattr(store, "root", ".") or ".")
    by_backend = {e.get("backend_station_id"): e
                  for e in registry.get("detectors", [])}
    return [m for m in store.mapping
            if m.get("backend_station_id") in by_backend]
