/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAnalyzeDataRouteImport } from './routes/_app.analyze-data'
import { Route as AppEvaluationRouteImport } from './routes/_app.evaluation'
import { Route as AppJudgeProbeRouteImport } from './routes/_app.judge-probe'
import { Route as AppNetworkHealthRouteImport } from './routes/_app.network-health'
import { Route as AppAlertsIndexRouteImport } from './routes/_app/alerts/index'
import { Route as AppAlertsAlertIdRouteImport } from './routes/_app/alerts/$alertId'
import { Route as AppInvestigationsIndexRouteImport } from './routes/_app/investigations/index'
import { Route as AppInvestigationsAlertIdRouteImport } from './routes/_app/investigations/$alertId'
import { Route as AppStationsIndexRouteImport } from './routes/_app/stations/index'
import { Route as AppStationsStationIdRouteImport } from './routes/_app/stations/$stationId'
import { Route as AppInvestigationsReplayAnomalyIdRouteImport } from './routes/_app.investigations.replay.$anomalyId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyzeDataRoute = AppAnalyzeDataRouteImport.update({
  id: '/analyze-data',
  path: '/analyze-data',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluationRoute = AppEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => AppRoute,
} as any)
const AppJudgeProbeRoute = AppJudgeProbeRouteImport.update({
  id: '/judge-probe',
  path: '/judge-probe',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkHealthRoute = AppNetworkHealthRouteImport.update({
  id: '/network-health',
  path: '/network-health',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsIndexRoute = AppAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsAlertIdRoute = AppAlertsAlertIdRouteImport.update({
  id: '/alerts/$alertId',
  path: '/alerts/$alertId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestigationsIndexRoute = AppInvestigationsIndexRouteImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestigationsAlertIdRoute =
  AppInvestigationsAlertIdRouteImport.update({
    id: '/investigations/$alertId',
    path: '/investigations/$alertId',
    getParentRoute: () => AppRoute,
  } as any)
const AppStationsIndexRoute = AppStationsIndexRouteImport.update({
  id: '/stations/',
  path: '/stations/',
  getParentRoute: () => AppRoute,
} as any)
const AppStationsStationIdRoute = AppStationsStationIdRouteImport.update({
  id: '/stations/$stationId',
  path: '/stations/$stationId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestigationsReplayAnomalyIdRoute =
  AppInvestigationsReplayAnomalyIdRouteImport.update({
    id: '/investigations/replay/$anomalyId',
    path: '/investigations/replay/$anomalyId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/analyze-data': typeof AppAnalyzeDataRoute
  '/evaluation': typeof AppEvaluationRoute
  '/judge-probe': typeof AppJudgeProbeRoute
  '/network-health': typeof AppNetworkHealthRoute
  '/alerts/$alertId': typeof AppAlertsAlertIdRoute
  '/investigations/$alertId': typeof AppInvestigationsAlertIdRoute
  '/stations/$stationId': typeof AppStationsStationIdRoute
  '/alerts/': typeof AppAlertsIndexRoute
  '/investigations/': typeof AppInvestigationsIndexRoute
  '/stations/': typeof AppStationsIndexRoute
  '/investigations/replay/$anomalyId': typeof AppInvestigationsReplayAnomalyIdRoute
}
export interface FileRoutesByTo {
  '/analyze-data': typeof AppAnalyzeDataRoute
  '/evaluation': typeof AppEvaluationRoute
  '/judge-probe': typeof AppJudgeProbeRoute
  '/network-health': typeof AppNetworkHealthRoute
  '/': typeof AppIndexRoute
  '/alerts/$alertId': typeof AppAlertsAlertIdRoute
  '/investigations/$alertId': typeof AppInvestigationsAlertIdRoute
  '/stations/$stationId': typeof AppStationsStationIdRoute
  '/alerts': typeof AppAlertsIndexRoute
  '/investigations': typeof AppInvestigationsIndexRoute
  '/stations': typeof AppStationsIndexRoute
  '/investigations/replay/$anomalyId': typeof AppInvestigationsReplayAnomalyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/analyze-data': typeof AppAnalyzeDataRoute
  '/_app/evaluation': typeof AppEvaluationRoute
  '/_app/judge-probe': typeof AppJudgeProbeRoute
  '/_app/network-health': typeof AppNetworkHealthRoute
  '/_app/': typeof AppIndexRoute
  '/_app/alerts/$alertId': typeof AppAlertsAlertIdRoute
  '/_app/investigations/$alertId': typeof AppInvestigationsAlertIdRoute
  '/_app/stations/$stationId': typeof AppStationsStationIdRoute
  '/_app/alerts/': typeof AppAlertsIndexRoute
  '/_app/investigations/': typeof AppInvestigationsIndexRoute
  '/_app/stations/': typeof AppStationsIndexRoute
  '/_app/investigations/replay/$anomalyId': typeof AppInvestigationsReplayAnomalyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze-data'
    | '/evaluation'
    | '/judge-probe'
    | '/network-health'
    | '/alerts/$alertId'
    | '/investigations/$alertId'
    | '/stations/$stationId'
    | '/alerts/'
    | '/investigations/'
    | '/stations/'
    | '/investigations/replay/$anomalyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analyze-data'
    | '/evaluation'
    | '/judge-probe'
    | '/network-health'
    | '/'
    | '/alerts/$alertId'
    | '/investigations/$alertId'
    | '/stations/$stationId'
    | '/alerts'
    | '/investigations'
    | '/stations'
    | '/investigations/replay/$anomalyId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/analyze-data'
    | '/_app/evaluation'
    | '/_app/judge-probe'
    | '/_app/network-health'
    | '/_app/'
    | '/_app/alerts/$alertId'
    | '/_app/investigations/$alertId'
    | '/_app/stations/$stationId'
    | '/_app/alerts/'
    | '/_app/investigations/'
    | '/_app/stations/'
    | '/_app/investigations/replay/$anomalyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analyze-data': {
      id: '/_app/analyze-data'
      path: '/analyze-data'
      fullPath: '/analyze-data'
      preLoaderRoute: typeof AppAnalyzeDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evaluation': {
      id: '/_app/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof AppEvaluationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/judge-probe': {
      id: '/_app/judge-probe'
      path: '/judge-probe'
      fullPath: '/judge-probe'
      preLoaderRoute: typeof AppJudgeProbeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network-health': {
      id: '/_app/network-health'
      path: '/network-health'
      fullPath: '/network-health'
      preLoaderRoute: typeof AppNetworkHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts/': {
      id: '/_app/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AppAlertsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts/$alertId': {
      id: '/_app/alerts/$alertId'
      path: '/alerts/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AppAlertsAlertIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investigations/': {
      id: '/_app/investigations/'
      path: '/investigations'
      fullPath: '/investigations/'
      preLoaderRoute: typeof AppInvestigationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investigations/$alertId': {
      id: '/_app/investigations/$alertId'
      path: '/investigations/$alertId'
      fullPath: '/investigations/$alertId'
      preLoaderRoute: typeof AppInvestigationsAlertIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stations/': {
      id: '/_app/stations/'
      path: '/stations'
      fullPath: '/stations/'
      preLoaderRoute: typeof AppStationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stations/$stationId': {
      id: '/_app/stations/$stationId'
      path: '/stations/$stationId'
      fullPath: '/stations/$stationId'
      preLoaderRoute: typeof AppStationsStationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investigations/replay/$anomalyId': {
      id: '/_app/investigations/replay/$anomalyId'
      path: '/investigations/replay/$anomalyId'
      fullPath: '/investigations/replay/$anomalyId'
      preLoaderRoute: typeof AppInvestigationsReplayAnomalyIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyzeDataRoute: typeof AppAnalyzeDataRoute
  AppEvaluationRoute: typeof AppEvaluationRoute
  AppJudgeProbeRoute: typeof AppJudgeProbeRoute
  AppNetworkHealthRoute: typeof AppNetworkHealthRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAlertsAlertIdRoute: typeof AppAlertsAlertIdRoute
  AppInvestigationsAlertIdRoute: typeof AppInvestigationsAlertIdRoute
  AppStationsStationIdRoute: typeof AppStationsStationIdRoute
  AppAlertsIndexRoute: typeof AppAlertsIndexRoute
  AppInvestigationsIndexRoute: typeof AppInvestigationsIndexRoute
  AppStationsIndexRoute: typeof AppStationsIndexRoute
  AppInvestigationsReplayAnomalyIdRoute: typeof AppInvestigationsReplayAnomalyIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyzeDataRoute: AppAnalyzeDataRoute,
  AppEvaluationRoute: AppEvaluationRoute,
  AppJudgeProbeRoute: AppJudgeProbeRoute,
  AppNetworkHealthRoute: AppNetworkHealthRoute,
  AppIndexRoute: AppIndexRoute,
  AppAlertsAlertIdRoute: AppAlertsAlertIdRoute,
  AppInvestigationsAlertIdRoute: AppInvestigationsAlertIdRoute,
  AppStationsStationIdRoute: AppStationsStationIdRoute,
  AppAlertsIndexRoute: AppAlertsIndexRoute,
  AppInvestigationsIndexRoute: AppInvestigationsIndexRoute,
  AppStationsIndexRoute: AppStationsIndexRoute,
  AppInvestigationsReplayAnomalyIdRoute: AppInvestigationsReplayAnomalyIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
